### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by skattoju** [opdev/opcap#105]
In theory should not have too many major side effects since we don't yet have any actions triggered by certain branches but opdevbot may not like it ..

One set of instructions are here:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by acmenezes** [comment]
@skattoju is there any impact to commit history? Can you confirm that. I couldn't see that from the docs. It only mentions urls I may have skipped it.

**Comment by skattoju** [comment]
I don't believe there is any impact to commit history tried it locally
```
 skattoju@skattoju-mac  ~/code/opcap   testing  git log --graph > /tmp/before.txt
 skattoju@skattoju-mac  ~/code/opcap   testing  git branch -m test
 skattoju@skattoju-mac  ~/code/opcap   test  git log --graph > /tmp/after.txt
 skattoju@skattoju-mac  ~/code/opcap   test  diff /tmp/before.txt /tmp/after.txt
```

**Comment by OchiengEd** [comment]
Generally, I would be apprehensive of making this change. Since there are a number of forks to the repo. Once the change is made on the upstream repository, there is likely going to be a need for all the forks to be recreated.
