### ISSUE TITLE
Add version command to opcap

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#111]
Add version command to opcap using compile time variables combined with ldxflags from the go build command as we can see in those examples here:

https://github.com/acmenezes/podtracer/blob/8abafad6961c13d5916b963a1982c2cfe88762a1/Makefile#L21-L27
https://github.com/acmenezes/podtracer/blob/8abafad6961c13d5916b963a1982c2cfe88762a1/cmd/version.go#L1-L34

We can start with version 0.0.1

**Comment by mgoerens** [comment]
Thanks for the examples. Very cool. I will add this to opcap.

I wonder if having the `GIT_USER` is really necessary. From my point of view it doesn't bring any added value, but I'm happy to hear any arguments in favor of `GIT_USER`.
