### ISSUE TITLE
--list-packages flag should also handle catalogsource and catalogsourcenamespace

### ISSUE THREAD

**Issue by mrhillsman** [opdev/opcap#116]
Currently when using --list-packages a complete list of names are returned but there is additional data required at least for the use case of running a single operator returned in the list. An example of this is the cert-manager operator.

```sh
Melvins-MacBook-Pro:opcap mrhillsman$ go run main.go check --list-packages | grep cert-manager
I0726 19:25:26.141403   41335 request.go:601] Waited for 1.054412913s due to client-side throttling, not priority and fairness, request: GET:https://api.exedb-sno-pool-two-c72xd.opdev.io:6443/apis/packages.operators.coreos.com/v1?timeout=32s
cert-manager
openshift-cert-manager-operator
Melvins-MacBook-Pro:opcap mrhillsman$ 
```

cert-manager is in the community-operators catalogsource

- [ ] --list-packages alone lists all packagemanifests (default behavior) but should include the catalogsource and catalogsourcenamespace
- [ ] --list-packages should work with catalogsource flag filtering returned package names based on catalogsource

**Comment by trgeiger** [comment]
The 2nd checkbox for filtering the output by Catalog Source was handled by Edmund in a previous PR.
