### ISSUE TITLE
--filter should verify operator exists in catalogsource

### ISSUE THREAD

**Issue by mrhillsman** [opdev/opcap#117]

**Comment by trgeiger** [comment]
@mrhillsman What is the desired behavior here? For when an operator does exist in the catalogsource, and for when it does not exist?

**Comment by mrhillsman** [comment]
@trgeiger 

- When operator exists in catalogsource execute the auditplan against said operator
- When operator does not exist fail with at least message stating operator does not exist in catalogsource {{catalogsource}}

**Comment by acmenezes** [comment]
So I just would like to point out that filter shouldn't be inside the operator package. This is check flag logic and not operator package logic. Operator provides the full data and check changes it as necessary to present information to user. I opened another issue to solve that refactor part https://github.com/opdev/opcap/issues/165 @trgeiger it's your choice, but if you feel comfortable you can try refactoring this a bit. If not feel free to check the package exist and just make that change. I'll keep this issue opened anyway.
