### ISSUE TITLE
Change module name to "github.com/opdev/opcap"

### ISSUE THREAD

**Issue by mgoerens** [opdev/opcap#121]
Currently the module is called `opcap`. I'm suggesting to rename it `github.com/opdev/opcap` as this seems to be a better practice (please feel free to contradict me).

This change implies to, at least:
- rename the module name in `go.mod`
- change all imports related to the opcap packages, for instance from `import "opcap/internal/operator"` to `import "github.com/opdev/opcap/internal/operator"`
- edit the ldflags of the build target in Makefile, for instance from `"-X 'opcap/cmd.GitCommit=$(GIT_COMMIT)'` to `"-X 'github.com/opdev/opcap/cmd.GitCommit=$(GIT_COMMIT)'`.

**Comment by mrhillsman** [comment]
Agreed unless there is discussion/concern this should live in a different org/namespace and changing again would be more difficult.

**Comment by mgoerens** [comment]
IMO a future renaming is always possible. If the module name at that time is `opcap` or something else (`github.com/opdev/opcap` for instance), that shouldn't make a difference
