### ISSUE TITLE
Move filter logic to check.go or other cmd level file

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#165]
Parameters from flags should have their logic as close as possible of the command being called. They don't belong to other packages. I believe we can refactor this to decouple the commands from their serving packages and keep them as independent as possible. This way changes in the command behaviors won't brake or demand changes on the internal packages.

**Comment by trgeiger** [comment]
Closing this per our discussion on 9/26--in summary: current state of this specific logic is fine and makes sense after a group discussion, but we should review the rest of the code base and make sure we are being consistent with how we partition the different packages.
