### ISSUE TITLE
Add Welcome message on PR page with contribution guideline links

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#181]
We need to add a message on the PR page to remember contributors about the need for well written issues that describe the problem the PRs are solving. That is to avoid the bad practice of accepting PRs without issues. The issues page should also have a similar  message.

**Comment by trgeiger** [comment]
So I'm assuming this will require setting up a bot/actions to put a comment with the reminder message about linking an issue. It also appears there are some bots out there that require linking an issue in the PR description before it will allow merging, i.e. https://github.com/nearform/github-action-check-linked-issues

I don't seem to have the ability to manage anything with our actions in this repository, however, so pinging @acmenezes @mrhillsman

**Comment by mrhillsman** [comment]
@acmenezes @trgeiger any reason we cannot rely on the contribution guidelines instead of introducing more complexity and/or code? I believe it reasonable to do one or both; update contribution.md, move contribution.md to the top of README.md. All PRs require an approval and anyone approving a PR should know such requirement(s).

**Comment by trgeiger** [comment]
I mean that's fine with me, and I think that's a good idea. I just was following along with Alex's idea of a message on the PR page, which would require this extra work to have a bot or whatever leave a comment.

**Comment by trgeiger** [comment]
Or can't we also make a pull request template?

**Comment by trgeiger** [comment]
Created a template in #191 which links to the contribution guidelines. I think this could be the best solution.

**Comment by trgeiger** [comment]
PR template is merged, closing
