### ISSUE TITLE
Clean resources before exiting when receiving SIGINT

### ISSUE THREAD

**Issue by mgoerens** [opdev/opcap#226]
## Is your feature request related to a problem? Please describe.
Currently, when interrupting the `check` command with SIGINT (Ctrl+C), opcap directly exits. This potentially leaves resources such as namespaces on the target kubernetes cluster. This is not "clean", and can lead to unexpected behavior on a subsequent run when using the same target cluster.

In my tests, I noticed for example the following behavior:
1. Run `opcap check` on a particular package.
2. Send SIGINT (Ctrl+C) when the corresponding namespace is created, but before the full audit ran.
3. At that moment the namespace exists on the cluster, with some resources in it (Deployment/ReplicaSet/Pod for running the Operator), but opcap is stopped.
4. Run the same `opcap check` command again (on the same package) and wait for completion.
5. opcap doesn't print the "Operator Install Report", but deletes the namespace.

```
[mgoerens@mgoerens opcap]$ opcap check --catalogsource=certified-operators --catalogsourcenamespace=openshift-marketplace --packages prometurbo-certified
I0909 15:19:26.650623   48768 request.go:601] Waited for 1.000534122s due to client-side throttling, not priority and fairness, request: GET:https://api.exedb-sno-pool-vg5zz.opdev.io:6443/apis/apiserver.openshift.io/v1?timeout=32s
^C     <------- Send SIGINT

[mgoerens@mgoerens opcap]$ oc get all -n opcap-prometurbo-certified
NAME                                       READY   STATUS    RESTARTS   AGE
pod/prometurbo-operator-55dfdb456d-nqbvg   1/1     Running   0          17s

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometurbo-operator   1/1     1            1           18s

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/prometurbo-operator-55dfdb456d   1         1         1       18s

[mgoerens@mgoerens opcap]$ opcap check --catalogsource=certified-operators --catalogsourcenamespace=openshift-marketplace --packages prometurbo-certified
I0909 15:19:56.992667   48892 request.go:601] Waited for 1.048798704s due to client-side throttling, not priority and fairness, request: GET:https://api.exedb-sno-pool-vg5zz.opdev.io:6443/apis/console.openshift.io/v1?timeout=32s
<------- Program exits without printing a report

[mgoerens@mgoerens opcap]$ oc get all -n opcap-prometurbo-certified
No resources found in opcap-prometurbo-certified namespace.

```

There might be other unexpected behaviors I haven't identified, or coming up in the future if we don't correctly clean up for instance CR or CRD.

## Describe the solution you'd like.

An elegant solution IMO would be to
- catch SIGINT and perform a clean-up of the created resources before exiting the program.
- add a timeout, so that the program eventually exits, even if all clean-up couldn't be performed.
- catch subsequent SIGINT: this should directly exit the program.
- provide the user with a message along the line: "SIGINT caught, performing clean-up ... Send SIGINT again to force exit"

This behavior is AFAIK pretty frequent in other command.

## Describe alternatives you've considered.

Alternatively (or better, additionally) we could look into ensuring that our audit suite correctly runs, even if the resources we want to create are already present. That actually raises other concerns, such as: How should opcap behaves if the namespace it intends to create already exists ?

However, correctly cleaning-up resources sounds to me as a better solution.

## Additional context.
- https://stackoverflow.com/questions/11268943/is-it-possible-to-capture-a-ctrlc-signal-sigint-and-run-a-cleanup-function-i

**Comment by acmenezes** [comment]
closed by #261
