### ISSUE TITLE
Level 1 Docs - Basic Install

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#3]
Add design docs with precise criteria on basic install including operator and operand, how it's tested, what can be found on the report and what is a nice to have on top of the mandatory criteria.

**Comment by acmenezes** [comment]
Hi @yashoza19 , I see that you are assigned in multiple issues. Do you want some help with this one here? I can take it over. Let me know.

**Comment by yashoza19** [comment]
Basic Level 1 documentation is closed by #91
