### ISSUE TITLE
Create methods to handle Kube Secrets

### ISSUE THREAD

**Issue by yashoza19** [opdev/opcap#33]
Add functions or methods to create, validate and delete kubernetes secrets.

**Comment by acmenezes** [comment]
@yashoza19 can you please clarify what secrets are we using at this moment? I'm not entirely sure which ones are valid for our use case after all the changes we've made.

**Comment by yashoza19** [comment]
@acmenezes We no longer require a secret with all the changes we have made to opcap. The secret was to store credentials to fetch bundle images from registries. We can delete this issue.
