### ISSUE TITLE
We are not testing all install modes

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#51]
For now we are just using the first supported install mode. We are not testing the other supported install modes. We need a way to choose which one or all of them.

**Comment by mrhillsman** [comment]
We are only testing one of the many supported installmodes by each operator. If the operator claims to support more than one installmode we want to allow testing any. Could be implemented via a flag to choose one or more installmode. --installmode [all|single|many|own]

**Comment by OchiengEd** [comment]
I can work on being able to target a specific install mode next.
