### ISSUE TITLE
[feature] Consider refactoring client kubeconfig logic

### ISSUE THREAD

**Issue by itroyano** [opdev/opcap#88]
Current State:

several flows in the code involve initializing a local client using `cfg, err := clientcmd.BuildConfigFromFlags("", os.Getenv("KUBECONFIG"))`.

This does 3 things:
1. makes every flow's function re-initialize a client from config, which may have already been initialized in a previous flow.
2. actively looking for a KUBECONFIG env var, and no fallbacks in case the user would like to read the default .kube or has provided the explicit flag.  often resulting in nasty errors.
3. tool initialization takes a client (client.go) where kubeconfig is being read with controller runtime's `kubeconfig, err := ctrl.GetConfig()`.   this is a hierarchical config loading function which also considers an explicit `--kubeconfig` flag, and can fall back to default.
this, together with (1), may lead to a situation where initialization is successful but then a flow would fail to load a config.  creating inconsistency.

Proposed Solutions:

1. have every localized flow do `ctrl.GetConfig()` instead of `BuildConfigFromFlags`.   this will ensure consistency.
2. (better in my opinion) use and re-use a central, get-able client, initialized using the controller runtime method.  this will both ensure consistency and prevent re-initializing clients which may have already been created.

**Comment by acmenezes** [comment]
HI @itroyano, thanks for the suggestion! Agreed. Can you please list what flows you saw that need refactoring so that we can plan this accordingly? Could please point out the lines on the code where you catch the problem? Thanks again!

**Comment by itroyano** [comment]
Hi @acmenezes 
basically all the checks that go through initializing a client from config
![image](https://user-images.githubusercontent.com/83590748/178975639-2534e7bb-98c0-44ba-9bbd-8e96481e8ecd.png)

vs the flows that go through 
![image](https://user-images.githubusercontent.com/83590748/178975906-d772aac3-507b-4b0c-89c4-b4dbc7c271e5.png)
which is the function that does `ctrl.GetConfig()`

I'll have a PR up with suggestions soon.

**Comment by acmenezes** [comment]
Hi @itroyano just passing by here. Is this one still relevant? Let me know if you need any help. And would be glad to see your suggestions.

**Comment by OchiengEd** [comment]
it does make sense to use the controller runtime `GetConfig()` method since it would use the precedence below:

* --kubeconfig flag pointing at a file
* KUBECONFIG environment variable pointing at a file
* In-cluster config if running in cluster
* $HOME/.kube/config if exists.

@itroyano Should I assign this to you?

**Comment by itroyano** [comment]
@OchiengEd it does.
Also I want to "centralize" the initialization of Client & Config.  have functions that want a client, fetch it with a "get" rather than trying to initialize locally.

@acmenezes code has changed so I'll need to look at the above places one more time.

**Comment by acmenezes** [comment]
Sure @itroyano, let me know if you need any help.
