### ISSUE TITLE
Create a CI system to do integration tests against a sample operator

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#9]
In order to verify the capability tool behaviour and correctness we need to have a sample operator with all the levels present in it and standardized to be used with this tool. With that we can simulate failures on specific levels and assert the results. This issue should be possibly broken in multiple parts since it entails a dedicated operator and bundle for testing, testing logic and a CI system configured. Placing the issue here for tracking the topic.

**Comment by mrhillsman** [comment]
- [ ] Prow (updated; was already in team cluster)
- [ ] Some simple jobs that can be used as example (golint or gofmt?)
- [ ] What is the sample operator?
- [ ] What if any integration test(s) already exist?
