### ISSUE TITLE
[cross feature] For failed operators list fail reasons or pre-requisites for installing or upgrading

### ISSUE THREAD

**Issue by itroyano** [opdev/opcap#93]
**Topic for discussion:** 

What should be done with “failed” status operators in the installation test or upgrade test?
Some operators would fail an automatic installation flow because of operator-specific requirements.

We can’t really expect what the requirements are. there could be endless possibilities for pre-requisites an operator may have, from requiring specific service accounts be created, to specific affinities on the cluster.

Operator authors tend to mention such requirements in the documentation/readme, or in the CSV `.spec.description`.

**Example:**

{"level":"info","message":"failed","package":"minio-operator","channel":"stable","installmode":"AllNamespaces"}
Controller manager pod and was stuck in pending state, due to “no nodes matched pod anti-affinity”.

**Suggestion:**

We could bring it up to OLM team to have requirements be listed as a `.spec.requirements` attribute in CSV (instead of in description or readme) ?
in such a case, OPCAP could automate steps for each failed operator, by reading that field and then have that included in the report, and/or doing some steps (possibly).

**Comment by acmenezes** [comment]
Thanks for this issue @itroyano ! I'll be working on this as my next step.

**Comment by acmenezes** [comment]
opcap now has a stdout print version of the report including Result, Reason and Message that can display primary information for operator failures.
Closed by #123
